# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_About_Dialog(object):
    def setupUi(self, About_Dialog):
        About_Dialog.setObjectName("About_Dialog")
        About_Dialog.resize(228, 265)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../run/media/oaaariasm/Local/Projects/Python/xfce-proxy/icon/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        About_Dialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(About_Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(About_Dialog)
        self.title_label.setMouseTracking(True)
        self.title_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_label.setTextFormat(QtCore.Qt.RichText)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.description_label = QtWidgets.QLabel(About_Dialog)
        self.description_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.description_label.setOpenExternalLinks(True)
        self.description_label.setObjectName("description_label")
        self.verticalLayout.addWidget(self.description_label)
        self.ok_buttonBox = QtWidgets.QDialogButtonBox(About_Dialog)
        self.ok_buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.ok_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.ok_buttonBox.setObjectName("ok_buttonBox")
        self.verticalLayout.addWidget(self.ok_buttonBox)

        self.retranslateUi(About_Dialog)
        self.ok_buttonBox.accepted.connect(About_Dialog.accept) # type: ignore
        self.ok_buttonBox.rejected.connect(About_Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(About_Dialog)

    def retranslateUi(self, About_Dialog):
        _translate = QtCore.QCoreApplication.translate
        About_Dialog.setWindowTitle(_translate("About_Dialog", "Acerca de"))
        self.title_label.setText(_translate("About_Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Asistente de configuración de proxy</p></body></html>"))
        self.description_label.setText(_translate("About_Dialog", "<html><head/><body><p>Ditribuido bajo licencia GPLv3</p><p>Creado por <a href=\"https://github.com/oaariasm\"><span style=\" text-decoration: underline; color:#3daee9;\">@oaariasm</span></a></p><p>Código fuente <a href=\"https://github.com/oaariasm/xfce-proxy\"><span style=\" text-decoration: underline; color:#3daee9;\">aquí</span></a></p></body></html>"))
